# Values for kubernetes-dashboard.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kubernetesui/dashboard
  tag: v2.0.0-rc5
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: kubernetes-dashboard

dashboard:
  service:
    type: ClusterIP
    port: 9090
  args:
    - --enable-insecure-login # Remove if using ingress with TLS
    - --authentication-mode=token
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 1001
    runAsGroup: 2001

proxy:
  enabled: true
  image: bitnami/oauth2-proxy
  service:
    type: ClusterIP
    port: 8080
  args:
    - --provider=oidc
    - --oidc-issuer-url=<OIDC URL>
    - --upstream=http://localhost:9090
    - --http-address=0.0.0.0:8080
    - --email-domain=*
    - --pass-basic-auth=false
    - --pass-access-token=false
    - --pass-authorization-header=true
    - --cookie-secure=false
    - --scope=openid profile email groups
    - --client-id=<OIDC ID>
    - --client-secret=<OIDC SECRET>
    - --client-secret=<BASE64 SECRET>
    - --ssl-insecure-skip-verify
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: k8s-dashboard.example.domain
        paths:
          - /

metricsScraper:
  image: kubernetesui/metrics-scraper
  tag: v1.0.3
  service:
    type: ClusterIP
    port: 8000
