apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{ include "kubernetes-dashboard.labels" . | indent 4 }}
  name: {{ include "kubernetes-dashboard.fullname" . }}
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
