apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-dashboard.name" . }}-settings
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kubernetes-dashboard.labels" . | indent 4 }}
