apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-dashboard.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kubernetes-dashboard.labels" . | indent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.proxy.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kubernetes-dashboard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
