apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-dashboard.name" . }}-certs
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kubernetes-dashboard.labels" . | indent 4 }}
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-dashboard.name" . }}-csrf
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kubernetes-dashboard.labels" . | indent 4 }}
type: Opaque
data:
  csrf: ""

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-dashboard.name" . }}-key-holder
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kubernetes-dashboard.labels" . | indent 4 }}
type: Opaque
